# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'operation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'RxDataSources', '~> 4.0'
  # Pods for operation

  target 'operationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'operationUITests' do
    # Pods for testing
  end

end
